default:
  golem_name: evalpam
  golem_version: 0.0.0.9000
  app_prod: no
  pg_host: fvafrsd-6v.forst.bwl.de
  pg_port: 5432.0
  pg_dbname: evalpam_db
  pg_user: evalpam_user
  admin_mailaddress: emailaddress@required.com
production:
  app_prod: yes
dev:
  golem_wd: golem::pkg_path()
